# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: master

name: render-rmarkdown.yaml

#permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
#    env:
#      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
#      -name: Set up pandoc
#      - uses: r-lib/actions/setup-pandoc@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Set up Renv
        uses: r-lib/actions/setup-renv@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
      - name: Debug - List files
        run: ls -al ..
            
      - name: Render Rmarkdown files and Commit Results
        run: |
          Rscript -e 'rmarkdown::render("README.Rmd")'

          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Hora atualizada" || echo "No changes to commit"
          git push origin || echo "No changes to commit"